import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://login.microsoftonline.com/2b69d099-dc61-447b-84c8-001733d8be3a/oauth2/authorize?client%5Fid=00000003%2D0000%2D0ff1%2Dce00%2D000000000000&response%5Fmode=form%5Fpost&response%5Ftype=code%20id%5Ftoken&resource=00000003%2D0000%2D0ff1%2Dce00%2D000000000000&scope=openid&nonce=EDFBE593298EBA380A92D7C8D60F13048EB593DFE009D72B%2DD59ADF8C820764ED16D2575DF12D627CE029D4C38D35D1E073F2444B026AEDA3&redirect%5Furi=https%3A%2F%2Fusfaa%2Esharepoint%2Ecom%2F%5Fforms%2Fdefault%2Easpx&state=OD0w&claims=%7B%22id%5Ftoken%22%3A%7B%22xms%5Fcc%22%3A%7B%22values%22%3A%5B%22CP1%22%5D%7D%7D%7D&wsucxt=1&cobrandid=11bd8083%2D87e0%2D41b5%2Dbb78%2D0bc43c8a8e8a&client%2Drequest%2Did=c9485aa1%2D60ee%2D6000%2D9b75%2D93f7558daa11")
    page.goto("https://login.microsoftonline.com/2b69d099-dc61-447b-84c8-001733d8be3a/oauth2/authorize?client%5Fid=00000003%2D0000%2D0ff1%2Dce00%2D000000000000&response%5Fmode=form%5Fpost&response%5Ftype=code%20id%5Ftoken&resource=00000003%2D0000%2D0ff1%2Dce00%2D000000000000&scope=openid&nonce=EDFBE593298EBA380A92D7C8D60F13048EB593DFE009D72B%2DD59ADF8C820764ED16D2575DF12D627CE029D4C38D35D1E073F2444B026AEDA3&redirect%5Furi=https%3A%2F%2Fusfaa%2Esharepoint%2Ecom%2F%5Fforms%2Fdefault%2Easpx&state=OD0w&claims=%7B%22id%5Ftoken%22%3A%7B%22xms%5Fcc%22%3A%7B%22values%22%3A%5B%22CP1%22%5D%7D%7D%7D&wsucxt=1&cobrandid=11bd8083%2D87e0%2D41b5%2Dbb78%2D0bc43c8a8e8a&client%2Drequest%2Did=c9485aa1%2D60ee%2D6000%2D9b75%2D93f7558daa11&sso_reload=true")
    page.get_by_label("Sign-in options").click()
    page.get_by_label("Face, fingerprint, PIN or").click()
    page.get_by_role("link", name="Other ways to sign in").click()
    page.get_by_placeholder("Email, phone, or Skype").click()
    page.get_by_placeholder("Email, phone, or Skype").fill("dominic.e.sisneros@faa.gov")
    page.get_by_placeholder("Email, phone, or Skype").press("Enter")
    with page.expect_popup() as page1_info:
        page.get_by_label("Check Status of my WRR. 1 of").click()
    page1 = page1_info.value
    page1.get_by_role("cell", name="Cannot be blank").get_by_role("textbox").click()
    page1.get_by_role("cell", name="Cannot be blank").get_by_role("textbox").fill("RTIR site survey")
    page1.locator("td").filter(has_text="ANCDENHNLLAXSEASLCOAK").locator("select").select_option("SLC")
    page1.locator("td").filter(has_text="WWT65 - TETON SSCWWT41 - SALT").get_by_role("combobox").select_option("WWT66 - NORTHERN UTAH SSC")
    page1.get_by_role("row", name="PROJECT FSEP LOC ID: PROJECT").get_by_role("textbox").first.click()
    page1.get_by_role("row", name="PROJECT FSEP LOC ID: PROJECT").get_by_role("textbox").first.fill("TEST")
    page1.get_by_role("row", name="PROJECT FSEP LOC ID: TEST").get_by_role("textbox").nth(1).click()
    page1.get_by_role("row", name="PROJECT FSEP LOC ID: TEST").get_by_role("textbox").nth(1).fill("RTR")
    page1.get_by_role("cell", name="TEST").get_by_role("textbox").click()
    page1.get_by_role("cell", name="TEST").get_by_role("textbox").fill("locid")
    page1.get_by_role("row", name="Building Name and #:").get_by_role("textbox").click()
    page1.get_by_role("row", name="Street Address: City, State,").get_by_role("textbox").first.click()
    page1.get_by_role("row", name="Street Address: City, State,").get_by_role("textbox").first.fill("993 north morton drive")
    page1.get_by_role("row", name="Street Address: 993 north").get_by_role("textbox").nth(1).click()
    page1.get_by_role("row", name="Street Address: 993 north").get_by_role("textbox").nth(1).fill("Salt lake city,ut, 84010")
    page1.get_by_role("row", name="Is this project in CWP?").locator("select").select_option("YES")
    page1.get_by_role("row", name="What is the JCN?").get_by_role("textbox").click()
    page1.get_by_role("row", name="What is the JCN?").get_by_role("textbox").click()
    page1.get_by_role("row", name="What is the JCN?").get_by_role("textbox").fill("21002467")
    page1.locator("textarea").first.click()
    page1.locator("textarea").first.fill("install wallboard")
    page1.get_by_role("link", name="Date Picker").first.click()
    page1.locator("#DatePickerIFrame").click()
    page1.locator("#DatePickerIFrame").content_frame().get_by_role("cell", name="October 16").click()
    page1.get_by_role("row", name="Date Picker", exact=True).get_by_role("link").click()
    page1.locator("#DatePickerIFrame").content_frame().get_by_role("button", name="October 18").click()
    page1.get_by_role("checkbox").first.check()
    page1.get_by_role("row", name="IF CONTRACTOR, COMPANY NAME").get_by_role("textbox").click()
    page1.get_by_role("row", name="IF CONTRACTOR, COMPANY NAME").get_by_role("textbox").fill("name")
    page1.get_by_role("row", name="NAME OF PERSON SUPERVISING").get_by_role("textbox").click()
    page1.get_by_role("row", name="NAME OF PERSON SUPERVISING").get_by_role("textbox").fill("supervvisor")
    page1.locator("textarea").nth(1).click()
    page1.locator("textarea").nth(1).fill("faa people, faa, people")
    page1.locator("textarea").nth(2).click()
    page1.locator("textarea").nth(2).fill("contractor people")
    page1.get_by_role("row", name="Sisneros, Dominic E (FAA) ,").locator("div").nth(3).click()
    page1.get_by_role("row", name="Sisneros, Dominic E (FAA) ,").locator("div").nth(3).click()
    page1.get_by_role("row", name="Sisneros, Dominic E (FAA) ,").locator("div").nth(3).click()
    page1.get_by_role("row", name="Sisneros, Dominic E (FAA) ,").locator("div").nth(3).click()
    page1.get_by_role("row", name="Distribute additional copies").get_by_role("textbox").click()
    page1.get_by_role("row", name="Distribute additional copies").get_by_role("textbox").fill("copies")
    page1.get_by_role("button", name="Add Attachments").click()
    with page1.expect_popup() as page2_info:
        page1.get_by_role("link", name="Add/View Attachments").click()
    page2 = page2_info.value
    page2.get_by_role("button", name="Upload a Document Upload a").click()
    page2.get_by_label("Upload Document").locator("iframe").content_frame().get_by_label("Enter or browse for uploading").click()
    page2.get_by_label("Upload Document").locator("iframe").content_frame().get_by_label("Enter or browse for uploading").set_input_files("SUN.RCO.21002467.rtir.transmittal.100.pdf")
    page2.get_by_label("Upload Document").locator("iframe").content_frame().locator("#ctl00_PlaceHolderMain_VersionCommentSection_ctl01_CheckInComment").click()
    page2.get_by_label("Upload Document").locator("iframe").content_frame().get_by_role("button", name="OK").click()
    page2.get_by_label("Upload Document").locator("iframe").content_frame().get_by_role("textbox", name="Description").click()
    page2.get_by_label("Upload Document").locator("iframe").content_frame().get_by_role("textbox", name="Description").fill("transmittal")
    page2.get_by_label("Upload Document").locator("iframe").content_frame().locator("input[name=\"ctl00\\$ctl30\\$g_0f462c9a_5ff7_407e_98d5_8a85d2c3bda5\\$ctl00\\$ctl02\\$ctl00\\$toolBarTbl\\$RightRptControls\\$ctl01\\$ctl00\\$diidIOGoBack\"]").click()
    page1.get_by_role("button", name="Save for Later").nth(1).click()
    page1.get_by_role("button", name="Return to WRR").click()
    page1.close()
    page2.locator("#s4-workspace").click()
    page2.close()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
